SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS O LEFT OUTER JOIN ANIMAL_INS I
ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE I.ANIMAL_ID IS NULL
ORDER BY O.ANIMAL_ID;

-- ANIMAL_OUTS를 기준으로 LEFT OUTER JOIN을 하면 I 입장에서 없는 데이터는 [I.ANIMAL_ID IS NULL]로 표현