SELECT b.BOOK_ID, DATE_FORMAT(b.PUBLISHED_DATE, '%Y-%m-%d') AS 'PUBLISHED_DATE'
FROM BOOK b
WHERE b.CATEGORY = '인문' AND b.PUBLISHED_DATE BETWEEN '2021-01-01' AND '2021-12-31'
ORDER BY b.PUBLISHED_DATE