-- SELF INNER JOIN
SELECT DISTINCT A.CART_ID
FROM CART_PRODUCTS A INNER JOIN CART_PRODUCTS B
ON A.CART_ID = B.CART_ID
WHERE A.NAME = 'Milk' AND B.NAME = 'Yogurt'
ORDER BY CART_ID;

-- SUBQUERY
SELECT DISTINCT CART_ID
FROM CART_PRODUCTS
WHERE CART_ID IN (
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Milk'
) AND NAME = 'Yogurt'
ORDER BY CART_ID;